### ISSUE TITLE
Cannot find module './shared/services/training-data.service'.

### ISSUE THREAD

**Issue by akhilpgeorge** [a-mma/amma-named-entity-recognition-frontend#1]
### **services missing.** 

when i tried `ng serve --open`, it shows `Cannot find module './shared/services/training-data.service'.`  is it intentionally excluded for any security reason??

**Comment by smqbit** [comment]
Hello Akhil...The error was due to the corrupted folder 'services'. The issue is resolved. master and develop branches are updated. Thanks buddy
